services:
  db:
    image: postgres:16
    container_name: unigear_postgres
    restart: unless-stopped
    env_file:
      - .env.docker
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: